-- MySQL Script generated by MySQL Workbench
-- Sun Aug 25 18:17:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hzq_base
-- -----------------------------------------------------
-- 系统基础服务,用户管理,角色管理

-- -----------------------------------------------------
-- Schema hzq_base
--
-- 系统基础服务,用户管理,角色管理
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hzq_base` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema hzq_log
-- -----------------------------------------------------
-- 操作日志记录库表
USE `hzq_base` ;

-- -----------------------------------------------------
-- Table `hzq_base`.`base_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_user` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_user` (
  `id` VARCHAR(64) NOT NULL,
  `username` VARCHAR(45) NULL COMMENT '用户名',
  `password` VARCHAR(45) NULL COMMENT '密码',
  `phone` VARCHAR(20) NULL COMMENT '注册手机号',
  `email` VARCHAR(45) NULL COMMENT '注册邮箱',
  `sex` CHAR(1) NULL COMMENT '0 男 1 女',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `hzq_base`.`base_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_role` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_role` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '数据值\n',
  `remarks` VARCHAR(255) NULL COMMENT '备注信息',
  `del_flag` CHAR(1) NULL DEFAULT '0' COMMENT '删除标记删除标记 ‘0’ 没有删除, ‘1’ 删除\n\n\n',
  `sys_flag` CHAR(1) NULL DEFAULT '0' COMMENT '系统角色标记 ‘0’ 不是 ‘1’是',
  `create_by` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `update_by` VARCHAR(64) NULL,
  `update_time` DATETIME NULL,
  `parent_id` VARCHAR(64) NULL COMMENT '父级别id 顶级默认是0',
  `parent_ids` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '角色管理表\n';


-- -----------------------------------------------------
-- Table `hzq_base`.`rl_user_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`rl_user_role` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`rl_user_role` (
  `id` VARCHAR(64) NOT NULL,
  `user_id` VARCHAR(64) NULL COMMENT '用户id',
  `role_Id` VARCHAR(64) NULL COMMENT '角色id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户角色关系表';


-- -----------------------------------------------------
-- Table `hzq_base`.`base_menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_menu` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_menu` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(100) NULL COMMENT '菜单名称',
  `parent_id` VARCHAR(64) NULL COMMENT '上级菜单id 顶级菜单父级id为0',
  `parent_ids` VARCHAR(1024) NULL COMMENT '所有父级id,用“,”顺序分隔',
  `href` VARCHAR(100) NULL COMMENT '链接',
  `icon` VARCHAR(100) NULL COMMENT '图标名称',
  `show_flag` CHAR(1) NULL DEFAULT '1' COMMENT '是否在菜单显示 0 否 1 是 默认是1',
  `permission` VARCHAR(255) NULL COMMENT '权限标示',
  `del_flag` CHAR(1) NULL DEFAULT '0' COMMENT '删除标记 0 否 1是',
  `description` VARCHAR(255) NULL COMMENT '描述',
  `sort` INT(10) NULL COMMENT '排序',
  `create_by` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `update_by` VARCHAR(64) NULL,
  `update_time` DATETIME NULL,
  `serve_id` VARCHAR(64) NULL COMMENT '服务id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '菜单表';


-- -----------------------------------------------------
-- Table `hzq_base`.`base_serve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_serve` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_serve` (
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '服务名称',
  `status` VARCHAR(45) NULL COMMENT '服务状态',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '服务管理表';


-- -----------------------------------------------------
-- Table `hzq_base`.`base_element`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_element` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_element` (
  `id` VARCHAR(64) NOT NULL,
  `menu_id` VARCHAR(64) NULL COMMENT '菜单id,按钮属于哪个菜单下面的',
  `name` VARCHAR(100) NULL COMMENT '按钮名称',
  `permission` VARCHAR(255) NULL COMMENT '权限标示',
  `href` VARCHAR(255) NULL COMMENT '链接',
  `create_by` VARCHAR(64) NULL,
  `ceate_time` DATETIME NULL,
  `update_by` VARCHAR(64) NULL,
  `update_time` DATETIME NULL,
  `element_type` VARCHAR(45) NULL COMMENT '元素类型,button,url等',
  `method` VARCHAR(10) NULL COMMENT '资源请求类型\n',
  `description` VARCHAR(255) NULL COMMENT '描述',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '按钮资源表';


-- -----------------------------------------------------
-- Table `hzq_base`.`rl_role_resource`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`rl_role_resource` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`rl_role_resource` (
  `id` VARCHAR(64) NOT NULL,
  `role_id` VARCHAR(64) NULL COMMENT '角色',
  `serve_id` VARCHAR(64) NULL COMMENT '服务id',
  `menu_id` VARCHAR(64) NULL COMMENT '菜单id',
  `element_id` VARCHAR(64) NULL COMMENT '元素id',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '角色和资源关系表';


-- -----------------------------------------------------
-- Table `hzq_base`.`base_dict`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_base`.`base_dict` ;

CREATE TABLE IF NOT EXISTS `hzq_base`.`base_dict` (
  `id` VARCHAR(64) NOT NULL,
  `code` VARCHAR(45) NULL COMMENT '数据编码',
  `name` VARCHAR(45) NULL COMMENT '字典名称',
  `dict_type` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL COMMENT '描述',
  `sort` INT(10) NULL,
  `del_flag` CHAR(1) NULL DEFAULT '0' COMMENT '0 否 1 是',
  `parent_id` VARCHAR(64) NULL COMMENT '父级id 顶层是 0',
  `parent_ids` VARCHAR(1024) NULL COMMENT '所有的父级别id',
  `create_by` VARCHAR(64) NULL,
  `create_time` DATETIME NULL,
  `update_by` VARCHAR(64) NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '数据字典';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
