-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 14:14:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hzq_base
-- -----------------------------------------------------
-- 系统基础服务,用户管理,角色管理
-- -----------------------------------------------------
-- Schema hzq_log
-- -----------------------------------------------------
-- 操作日志记录库表

-- -----------------------------------------------------
-- Schema hzq_log
--
-- 操作日志记录库表
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hzq_log` DEFAULT CHARACTER SET utf8 ;
USE `hzq_log` ;

-- -----------------------------------------------------
-- Table `hzq_log`.`log_login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_log`.`log_login` ;

CREATE TABLE IF NOT EXISTS `hzq_log`.`log_login` (
  `int` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `login_name` VARCHAR(50) NULL COMMENT '登陆账号',
  `ip` VARCHAR(45) NULL COMMENT '登陆ip',
  `browser` VARCHAR(255) NULL COMMENT '浏览器类型',
  `os` VARCHAR(255) NULL COMMENT '操作系统',
  `msg` VARCHAR(255) NULL COMMENT '提示信息',
  `create_time` DATETIME NULL COMMENT '登陆时间',
  PRIMARY KEY (`int`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户登陆日志';


-- -----------------------------------------------------
-- Table `hzq_log`.`log_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hzq_log`.`log_operation` ;

CREATE TABLE IF NOT EXISTS `hzq_log`.`log_operation` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `login_name` VARCHAR(128) NULL COMMENT '操作人',
  `url` VARCHAR(255) NULL COMMENT '请求的路径',
  `ip` VARCHAR(45) NULL COMMENT 'Ip地址',
  `params` VARCHAR(512) NULL COMMENT '请求参数',
  `create_time` DATETIME NULL COMMENT '操作时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户操作相关日志';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
